services:
  ingress:
    container_name: taidoton-ingress
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - client
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  client:
    container_name: taidoton-client
    build: ./client
    command: "sh -c 'npm install; npm run start'"
    volumes:
      - ./client:/app
      - /node_modules
    depends_on:
      - server
  server:
    container_name: taidoton-server
    command: "sh -c 'npm install; npm run start:dev'"
    build: ./server
    volumes:
      - ./server:/app
      - /node_modules